# Generated by Django 4.2 on 2024-04-02 17:10

import django.core.validators
from django.db import migrations, models
import jwt_upload_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to=jwt_upload_app.validators.name_file, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
