# Generated by Django 4.2 on 2024-04-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('secret_phrase', models.TextField(max_length=100)),
                ('user_token', models.TextField(max_length=300)),
                ('uuid_saved', models.UUIDField()),
            ],
        ),
    ]
